[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Room3b"
description = "Mark Hall's main site"
requires-python = ">=3.10"
keywords = []
authors = [{ name = "Mark Hall", email = "mark.hall@work.room3b.eu" }]
classifiers = []
dependencies = []
version = "1.0.0"

[project.urls]
Documentation = "http://edition.com"
Issues = "http://edition.com"
Source = "http://edition.com"

[tool.hatch.envs.default]
dependencies = ["uEdition<2.1,>=2.0.0b1", "uEdition-editor<2.1,>=2.0.0b6"]
skip-install = true

[tool.hatch.envs.default.scripts]
build = "uEdition build {args}"
serve = "uEdition serve {args}"
update = "uEdition update {args}"
migrate = "uEdition migrate {args}"
language = "uEdition language {args}"
